packages:
  clean-architecture:
    config:
      recursive: true
      with-expecter: true
  clean-architecture/domain:
    config:
      recursive: true
      with-expecter: true
  github.com/user/project/subpkg2:
    config:
      recursive: true
      with-expecter: true