// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	user_domain "clean-architecture/domain/user"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IUserRepository is an autogenerated mock type for the IUserRepository type
type IUserRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: c, userID
func (_m *IUserRepository) Delete(c context.Context, userID string) error {
	ret := _m.Called(c, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: c
func (_m *IUserRepository) Fetch(c context.Context) ([]user_domain.User, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []user_domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]user_domain.User, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []user_domain.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: c, email
func (_m *IUserRepository) GetByEmail(c context.Context, email string) (*user_domain.User, error) {
	ret := _m.Called(c, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *user_domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user_domain.User, error)); ok {
		return rf(c, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user_domain.User); ok {
		r0 = rf(c, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: c, id
func (_m *IUserRepository) GetByID(c context.Context, id string) (*user_domain.User, error) {
	ret := _m.Called(c, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user_domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user_domain.User, error)); ok {
		return rf(c, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user_domain.User); ok {
		r0 = rf(c, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUsername provides a mock function with given fields: c, username
func (_m *IUserRepository) GetByUsername(c context.Context, username string) (*user_domain.User, error) {
	ret := _m.Called(c, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *user_domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user_domain.User, error)); ok {
		return rf(c, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user_domain.User); ok {
		r0 = rf(c, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: c, email, user
func (_m *IUserRepository) Upsert(c context.Context, email string, user *user_domain.User) (*user_domain.Response, error) {
	ret := _m.Called(c, email, user)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *user_domain.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *user_domain.User) (*user_domain.Response, error)); ok {
		return rf(c, email, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *user_domain.User) *user_domain.Response); ok {
		r0 = rf(c, email, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user_domain.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *user_domain.User) error); ok {
		r1 = rf(c, email, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserRepository creates a new instance of IUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepository {
	mock := &IUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
