// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	unit "clean-architecture/domain/unit"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IUnitRepository is an autogenerated mock type for the IUnitRepository type
type IUnitRepository struct {
	mock.Mock
}

// CreateOne provides a mock function with given fields: ctx, _a1
func (_m *IUnitRepository) CreateOne(ctx context.Context, _a1 *unit.Unit) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *unit.Unit) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOne provides a mock function with given fields: ctx, unitID
func (_m *IUnitRepository) DeleteOne(ctx context.Context, unitID string) error {
	ret := _m.Called(ctx, unitID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, unitID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchByID provides a mock function with given fields: ctx, unitID
func (_m *IUnitRepository) FetchByID(ctx context.Context, unitID string) (*unit.Unit, error) {
	ret := _m.Called(ctx, unitID)

	if len(ret) == 0 {
		panic("no return value specified for FetchByID")
	}

	var r0 *unit.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*unit.Unit, error)); ok {
		return rf(ctx, unitID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *unit.Unit); ok {
		r0 = rf(ctx, unitID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unit.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, unitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchMany provides a mock function with given fields: ctx
func (_m *IUnitRepository) FetchMany(ctx context.Context) ([]unit.Unit, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMany")
	}

	var r0 []unit.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]unit.Unit, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []unit.Unit); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]unit.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchToDeleteMany provides a mock function with given fields: ctx
func (_m *IUnitRepository) FetchToDeleteMany(ctx context.Context) (*[]unit.Unit, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchToDeleteMany")
	}

	var r0 *[]unit.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]unit.Unit, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]unit.Unit); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]unit.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOne provides a mock function with given fields: ctx, unitID, _a2
func (_m *IUnitRepository) UpdateOne(ctx context.Context, unitID string, _a2 unit.Unit) error {
	ret := _m.Called(ctx, unitID, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, unit.Unit) error); ok {
		r0 = rf(ctx, unitID, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertOne provides a mock function with given fields: ctx, id, _a2
func (_m *IUnitRepository) UpsertOne(ctx context.Context, id string, _a2 *unit.Unit) (*unit.Unit, error) {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOne")
	}

	var r0 *unit.Unit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *unit.Unit) (*unit.Unit, error)); ok {
		return rf(ctx, id, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *unit.Unit) *unit.Unit); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unit.Unit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *unit.Unit) error); ok {
		r1 = rf(ctx, id, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUnitRepository creates a new instance of IUnitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUnitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUnitRepository {
	mock := &IUnitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
